function OAS_RICH(position) {
if (position == 'Left1') {
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('<script type="text/javascript">\n');
document.write ('//<![CDATA[\n');
document.write ('var filePath                     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/Casanet_Iam/ap_Phony_Tout_Temps_lateral/phony.swf/1399625691";\n');
document.write ('var TFSMFlash_PRETAG             = "";\n');
document.write ('var TFSMFlash_POSTTAG            = "";\n');
document.write ('var TFSMFlash_VERSION            = "8";\n');
document.write ('var TFSMFlash_WMODE              = "window";\n');
document.write ('\n');
document.write ('			var TFSMFlash_OASCLICK           = "http://pub.menara.ma/5c/www.iam2.ma/_layouts/SharepointFreeSms/L38/1076002036/Left1/Casanet_Iam/ap_Phony_Tout_Temps_lateral/ap_Phony_Tout_Temps_lateral.html/4b63683276315367664c6f4141453242?www.iam.ma/Particuliers/Fixe/ABONNEMENTS/Formulesdabonnement/Phony/Pages/PhonyClassique.aspx";\n');
document.write ('	\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE   = "?clickTag="+TFSMFlash_OASCLICK + "";\n');
document.write ('var TFSMFlash_SWFFILE            = filePath + TFSMFlash_SWFCLICKVARIABLE;\n');
document.write ('var TFSMFlash_FSCOMMAND          = "";\n');
document.write ('var TFSMFlash_IMAGEALTERNATE     = "";\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_OASALTTEXT         = "";\n');
document.write ('var TFSMFlash_OASTARGET          = "_blank";\n');
document.write ('var TFSMFlash_OASPROTOCOL        = "http://";\n');
document.write ('var TFSMFlash_OASDIM             = "width=');
document.write ("'");
document.write ('180px');
document.write ("'");
document.write (' height=');
document.write ("'");
document.write ('155px');
document.write ("'");
document.write ('";\n');
document.write ('var TFSMFlash_OASADID            = "OAS_RMF_Left1_FLASH";\n');
document.write ('document.write("<"+"scr"+"ipt type=\\');
document.write ('"text/javascript\\');
document.write ('" src=\\');
document.write ('"http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/Casanet_Iam/ap_Phony_Tout_Temps_lateral/TFSMFlashWrapper301.js/1399625691\\');
document.write ('"><\\');
document.write ('/scr"+"ipt"+">");\n');
document.write ('//]]>\n');
document.write ('</script>\n');
document.write ('\n');
}
if (position == 'Left2') {
document.write ('<A HREF="http://pub.menara.ma/5c/www.iam2.ma/_layouts/SharepointFreeSms/1857723593/Left2/default/empty.gif/4b63683276315367664c6f4141453242?x" target="_top"><IMG SRC="http://imageceu1.247realmedia.com/0/default/empty.gif"  WIDTH=1 HEIGHT=1 ALT="" BORDER=0 BORDER="0"></A>');
}
if (position == 'Left3') {
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('<script type="text/javascript">\n');
document.write ('//<![CDATA[\n');
document.write ('var filePath                     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/Casanet_Iam/AP_PRO-RefonteForfaitsBusiness180-150/AP_PRO-RefonteForfaitsBusiness180-150.swf/1375108026";\n');
document.write ('var TFSMFlash_PRETAG             = "";\n');
document.write ('var TFSMFlash_POSTTAG            = "";\n');
document.write ('var TFSMFlash_VERSION            = "8";\n');
document.write ('var TFSMFlash_WMODE              = "transparent";\n');
document.write ('\n');
document.write ('			var TFSMFlash_OASCLICK           = "http://pub.menara.ma/5c/www.iam2.ma/_layouts/SharepointFreeSms/L38/963485980/Left3/Casanet_Iam/AP_PRO-RefonteForfaitsBusiness180-150/AP_PRO-RefonteForfaitsBusiness180-150.html/4b63683276315367664c6f4141453242?www.iam.ma/Professionnels/Mobile/VoixMobile/Pages/ForfaitBusinessClass.aspx?categorie=forf_bus_class";\n');
document.write ('	\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE   = "?clickTag="+TFSMFlash_OASCLICK + "";\n');
document.write ('var TFSMFlash_SWFFILE            = filePath + TFSMFlash_SWFCLICKVARIABLE;\n');
document.write ('var TFSMFlash_FSCOMMAND          = "";\n');
document.write ('var TFSMFlash_IMAGEALTERNATE     = "";\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_OASALTTEXT         = "";\n');
document.write ('var TFSMFlash_OASTARGET          = "_blank";\n');
document.write ('var TFSMFlash_OASPROTOCOL        = "http://";\n');
document.write ('var TFSMFlash_OASDIM             = "width=');
document.write ("'");
document.write ('180px');
document.write ("'");
document.write (' height=');
document.write ("'");
document.write ('155px');
document.write ("'");
document.write ('";\n');
document.write ('var TFSMFlash_OASADID            = "OAS_RMF_Left3_FLASH";\n');
document.write ('document.write("<"+"scr"+"ipt type=\\');
document.write ('"text/javascript\\');
document.write ('" src=\\');
document.write ('"http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/Casanet_Iam/AP_PRO-RefonteForfaitsBusiness180-150/TFSMFlashWrapper301.js/1375108026\\');
document.write ('"><\\');
document.write ('/scr"+"ipt"+">");\n');
document.write ('//]]>\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('\n');
}
}
